apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-mmyers-org-tls
spec:
  secretName: k8s-mmyers-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mmyers.org
  dnsNames:
    - k8s.mmyers.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mmyers.org
          - k8s.mmyers.org